ERROR - 2025-02-20 16:08:20 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:08:20 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 16:08:20 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:08:20 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 16:08:23 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:08:23 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 16:08:23 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:08:23 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 16:08:26 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:08:26 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 16:08:27 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:08:27 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 16:08:30 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:08:30 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 16:08:30 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:08:30 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 16:08:33 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:08:33 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 16:08:33 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:08:33 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 16:08:35 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:08:35 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 16:08:35 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:08:35 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 16:09:16 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:09:16 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 16:09:16 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:09:16 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 16:09:33 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:09:33 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 16:09:33 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:09:33 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 16:09:47 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:09:47 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 16:09:47 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:09:47 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 16:10:56 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:10:56 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 16:10:56 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:10:56 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 16:13:06 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:13:06 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 16:13:06 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:13:06 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 16:13:14 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:13:14 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 16:13:15 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:13:15 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 16:15:41 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:15:41 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 16:15:41 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:15:41 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 16:16:33 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:16:33 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\BookingController.php(16): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\BookingController->getPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 16:16:33 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:16:33 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\UserPetController.php(13): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\UserPetController->getUserPetList()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2025-02-20 16:17:16 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u372271345_petz'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php(185): mysqli->real_connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#2 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\projects\Petz24\app\Controllers\MyBookingController.php(28): CodeIgniter\Database\BaseConnection->query()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\MyBookingController->getMyBooking()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#6 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#7 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\projects\Petz24\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect()
#1 C:\xampp\htdocs\projects\Petz24\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\projects\Petz24\app\Controllers\MyBookingController.php(28): CodeIgniter\Database\BaseConnection->query()
#3 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(941): App\Controllers\MyBookingController->getMyBooking()
#4 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
#5 C:\xampp\htdocs\projects\Petz24\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
#6 C:\xampp\htdocs\projects\Petz24\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-02-20 16:17:16 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\MyBookingController.php(28): CodeIgniter\Database\BaseConnection->query()
 3 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\MyBookingController->getMyBooking()
 4 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest()
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
